# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: zc706_r1.0.ucf.xdc

# IP: ip/cic_x10_0/cic_x10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cic_x10_0 || ORIG_REF_NAME==cic_x10_0} -quiet] -quiet
